stages:
  - deploy

swarm:
  image: docker:20
  stage: deploy
  script:
    - export DOCKER_CERT_PATH=$DEPLOY_DOCKER_CERT_PATH
    - export DOCKER_TLS_VERIFY=$DEPLOY_DOCKER_TLS_VERIFY
    - mkdir -p $DOCKER_CERT_PATH
    - cp $DEPLOY_DOCKER_TLS_CACERT $DOCKER_CERT_PATH/ca.pem
    - cp $DEPLOY_DOCKER_TLS_CERT $DOCKER_CERT_PATH/cert.pem
    - cp $DEPLOY_DOCKER_TLS_KEY $DOCKER_CERT_PATH/key.pem
    - cd deploy
    - docker stack deploy -c docker-compose.yml certbot
