# GitLab pipeline configuration for certbot
#
# This uses Ansible to manage an NFS export on my NFS server and Docker to
# deploy it to my Swarm server.
stages:
  - infra
  - deploy

storage:
  stage: infra
  image:
    name: code.home.jbeard.dev:5050/homelab/platform/homelab-base/ansible-tool:latest
    entrypoint: ['']
  before_script:
    - set -a
    - cp $SSH_PRIVATE_KEY /home/ansible/.ssh/id_rsa && chmod 400 /home/ansible/.ssh/id_rsa
  script:
    - cd deploy/playbook
    - ansible-galaxy install -r requirements.yml
    - ansible-playbook -i inventory.ini -u deployer -b nfs.yml

swarm:
  image: docker:24
  stage: deploy
  before_script:
    - export DOCKER_CERT_PATH=$DEPLOY_DOCKER_CERT_PATH
    - export DOCKER_TLS_VERIFY=$DEPLOY_DOCKER_TLS_VERIFY
    - export DOCKER_HOST=$DEPLOY_DOCKER_HOST
    - mkdir -p $DOCKER_CERT_PATH
    - cp $DEPLOY_DOCKER_TLS_CACERT $DOCKER_CERT_PATH/ca.pem
    - cp $DEPLOY_DOCKER_TLS_CERT $DOCKER_CERT_PATH/cert.pem
    - cp $DEPLOY_DOCKER_TLS_KEY $DOCKER_CERT_PATH/key.pem
  script:
    - cd deploy
    - docker stack deploy -c docker-compose.yml certbot
